insert into parking_users (id, email, acc_password, mobileno)
values (1, 'pasapi@au1.ibm.com', 'apples', '0411151350');

insert into parking_users (id, email, acc_password, mobileno)
values (2, 'mthite@au1.ibm.com', 'welcome1', '0411151350');


insert into ticket_events(event_id, event_date, event_name, location, standium, user_id)
values (72651, '2015-10-12', 'Rugby', 'ANZ Stadium', 'Sydeny Olympic Park', 1);

insert into ticket_events(event_id, event_date, event_name, location, standium, user_id)
values (72652, '2015-10-12', 'Rugby', 'ANZ Stadium', 'Sydeny Olympic Park', 2);

insert into parking_locations(id, available_car_parks, location_name, parkinglocation, parking_maps_url)
values (1, 42, 'SOP', '2DFA', 'https://www.google.com.au/maps/dir/%27%27/Sydney+Olympic+Park+NSW+2127/@-33.8519196,151.033,13z/data');

insert into parking_locations(id, available_car_parks, location_name, parkinglocation, parking_maps_url)
values (2, 6, 'SOP', '4DFA', 'https://www.google.com.au/maps/dir/%27%27/Sydney+Olympic+Park+NSW+2127/@-33.8519196,151.033,13z/data');

insert into parking_locations(id, available_car_parks, location_name, parkinglocation, parking_maps_url)
values (3, 3, 'SOP', '10DFA', 'https://www.google.com.au/maps/dir/%27%27/Sydney+Olympic+Park+NSW+2127/@-33.8519196,151.033,13z/data');

/*
Hibernate: create table parking_locations (id bigint generated by default as identity, available_car_parks integer not null, location_name varchar(255), parkinglocation varchar(255), parking_maps_url varchar(255), primary key (id))
Hibernate: create table parking_users (id bigint generated by default as identity, acc_password varchar(255), email varchar(255), mobileno varchar(255), primary key (id))
Hibernate: create table ticket_events (event_id bigint generated by default as identity, event_date date, event_name varchar(255), location varchar(255), standium varchar(255), user_id bigint, primary key (event_id))
*/